version: '2'
services:
  queue:
    image: redis:4-alpine
    restart: unless-stopped
    volumes:
      - ./data/queue:/data
    command: redis-server --appendonly yes
  bot:
    build: .
    links:
      - queue
    ports:
      - 8080:8080
    user: "${UID}:${GID}"
    env_file:
      - ./environment
    volumes:
      - ./data/cache:/app/run/.cache
      - ./data/simple-index:/app/run/simple-index
    restart: unless-stopped
    command: python -m oca_github_bot
    depends_on:
      - queue
  worker:
    build: .
    links:
      - queue
    user: "${UID}:${GID}"
    env_file:
      - ./environment
    volumes:
      - ./data/cache:/app/run/.cache
      - ./data/simple-index:/app/run/simple-index
    restart: unless-stopped
    command: celery worker --concurrency=2 --app=oca_github_bot.queue.app --loglevel=INFO
    depends_on:
      - queue
  beat:
    build: .
    links:
      - queue
    user: "${UID}:${GID}"
    env_file:
      - ./environment
    volumes:
      - ./data/cache:/app/run/.cache
      - ./data/simple-index:/app/run/simple-index
    restart: unless-stopped
    command: celery beat --app=oca_github_bot.queue.app
    depends_on:
      - queue
  monitor:
    build: .
    links:
      - queue
    ports:
      - 5555:5555
    user: "${UID}:${GID}"
    env_file:
      - ./environment
    restart: unless-stopped
    command: flower --app=oca_github_bot.queue.app
    depends_on:
      - queue
